async function getUsers (req: Request, res: Response){
    try{

    }catch (error){

    }
}